### ISSUE TITLE
curl command for install

### ISSUE THREAD

**Issue by fawadasaurus** [wasmflow/wasmflow#45]
**Is your feature request related to a problem? Please describe.**
Installing wasmflow/wafl should be easy like it is to install home-brew.  Here is how brew is installed.
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Propose a solution**
There should be a curl command similar to the following to install wasmflow:
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/wasmflow/wasmflow/HEAD/install.sh)"
```

**Describe alternatives you've considered**
None

**Additional context**
Just an easier way to reduce friction to get started.

**Comment by jsoverson** [comment]
Added one-line instructions to wasmflow.com to address this issue. The source for the installer is in https://github.com/wasmflow/wasmflow-installer
